[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."warm-camera"]
  schedule = "*/4 * * * *"

[[redirects]]
  from = "/api/camera"
  to = "/.netlify/functions/camera"
  status = 200

[functions."push-send-daily"]
  schedule = "28 22 * * *"

